### ISSUE TITLE
ALPN not support on Ubuntu14.04

### ISSUE THREAD

**Issue by sapjunior** [cryptofuture/nginx-hda-bundle#2]
https://alex.bouma.me/recompile-nginx-with-openssl-1-0-2-for-http-2-via-alpn-ubuntu-14-04/

Could you please compile nginx with  OpenSSL 1.0.2+ (for ubuntu 14.04)? HTTP2 isn't working due to only NPN is support!

**Comment by cryptofuture** [comment]
This is the bad thing to do. Last openssl version in trusty as for this post time is 1.0.1f-1ubuntu2.21. And openssl is a critical package, often updated by secure team in Ubuntu. Also to compile it with newer then repository version I need to include it in PPA or link PPA with 3rd party PPA. I can't handle really fast openssl updates myself and totally don't like that idea.
You better use xenial in your case. Since openssl is critical and freq updated (with security updates) package, using newer, but not patched in time openssl version could ruin things for your in order you can't easily predict.
